# Generated by Django 5.1.3 on 2024-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(help_text='ссылка в формате http/...', verbose_name='ссылка')),
                ('name', models.CharField(help_text='максимальная длина 255 символов', max_length=255, verbose_name='название')),
                ('vk_id', models.CharField(help_text='максимальная длина 255 символов', max_length=255, unique=True, verbose_name='VK id')),
                ('thumbnail_url', models.TextField(help_text='ссылка в формате http/...', verbose_name='ссылка на миниатюру')),
                ('view_count', models.PositiveIntegerField(help_text='положительное число', verbose_name='число просмотров')),
                ('adding_date', models.DateTimeField(verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'клип',
                'verbose_name_plural': 'клипы',
                'ordering': ('-adding_date',),
            },
        ),
    ]
