# Generated by Django 5.1.3 on 2024-12-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkClipInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_url', models.TextField(unique=True, verbose_name='ссылка на клип')),
            ],
            options={
                'verbose_name': 'ссылка на вк клип',
                'verbose_name_plural': 'ссылки на вк клипы',
            },
        ),
    ]
