# Generated by Django 5.1.3 on 2024-12-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.BigIntegerField(unique=True, verbose_name='Штрихкод'),
        ),
    ]
