# Generated by Django 5.1.3 on 2024-12-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_volume_productphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productphoto',
            options={'verbose_name': 'фото', 'verbose_name_plural': 'фото товара'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
    ]
