# Generated by Django 5.1.3 on 2024-12-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remains',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток'),
        ),
    ]
